### ISSUE TITLE
Missing ")" in snippets

### ISSUE THREAD

**Issue by DJ-Andrey-sXe** [html5andblog/quickjs-brackets-extension#2]
quickJS 0.0.4.
"Doc Ready" menu item result in code below. It misses ")".

```javascript
$(document).ready(function($){

};
```

The same in "doc ready nocnflict", "windows resize" and "each array" snippets.

**Comment by html5andblog** [comment]
Hi DJ Andrey,

Thanks for bringing this to my attention.

I've updated it now and corrected the issue.

Thanks Again.
